### ISSUE TITLE
Release target does not work

### ISSUE THREAD

**Issue by balhoff** [obophenotype/porifera-ontology#19]
@cmungall do you have uncommitted files that could make `make prepare_release` work? Problem here:

https://github.com/obophenotype/porifera-ontology/blob/78b05b37f75ce13bb63870360fb37bb143093f9f/src/ontology/Makefile#L43-L45

**Comment by cmungall** [comment]
I think the ttl is just the direct transform of the owl, as arq doesn't understand functional syntax.

but we can now just replace arq with `robot query`

**Comment by balhoff** [comment]
I should have been more clear, this file is missing:

```
File not found: sparql/getSeed.rq
make: *** [imports/seed.txt] Error 2
```
